### ISSUE TITLE
Contact request

### ISSUE THREAD

**Issue by X3R0-FR** [hytools/hy-tools#1]
Hello @hytools ,
I'm taking the liberty of creating a Github issue because I'm trying to contact you. I have a development project that will require the username ‘hytools’. I would like to know if it is possible to recover it.
Thank you in advance for your feedback, whether positive or negative.

You can also contact me by e-mail at x3r0.a@outlook.com to discuss the matter or send me your reply.

Looking forward to hearing from you

**Comment by hytools** [comment]
I'm very sorry for taking this name, if you can understand.
Since I haven't logged in to my account for a long time, I'm not aware of this happening, so I'm very sorry.
Have a nice day!
